const data = {
	products: [
		{
			name: "Free Shirt",
			category: "Shirts",
			image: "/images/shirt1.jpg",
			price: 70,
			brand: "Nike",
			rating: 4.5,
			numReviews: 10,
			countInStocks: 20,
			description: "A popular shirt",
			slug: "free-shirt",
		},
		{
			name: "Casual Shirt",
			category: "Shirts",
			image: "/images/shirt2.jpg",
			price: 70,
			brand: "Adidas",
			rating: 4.5,
			numReviews: 10,
			countInStocks: 20,
			description: "A popular shirt",
			slug: "casual-shirt",
		},
		{
			name: "Casual and Stylish Shirt",
			category: "Shirts",
			image: "/images/shirt3.jpg",
			price: 65,
			brand: "Nike",
			rating: 3.5,
			numReviews: 3,
			countInStocks: 10,
			description: "A popular shirt",
			slug: "casual-and-stylish-shirt",
		},
		{
			name: "Free Pant",
			category: "Pants",
			image: "/images/pants1.jpg",
			price: 70,
			brand: "Nike",
			rating: 4.5,
			numReviews: 10,
			countInStocks: 20,
			description: "A popular pant",
			slug: "free-pant",
		},
		{
			name: "Casual Pant",
			category: "Pants",
			image: "/images/pants2.jpg",
			price: 70,
			brand: "Adidas",
			rating: 4.5,
			numReviews: 10,
			countInStocks: 20,
			description: "A popular pant",
			slug: "casual-pant",
		},
		{
			name: "Casual and Stylish Pant",
			category: "Pants",
			image: "/images/pants3.jpg",
			price: 70,
			brand: "Crocodile",
			rating: 4.5,
			numReviews: 10,
			countInStocks: 20,
			description: "A popular pant",
			slug: "casual-and-stylish-pant",
		},
	],
};

export default data;
